# Generated by Django 4.2.7 on 2023-12-04 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_material_shape_remove_product_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='shape',
        ),
        migrations.AddField(
            model_name='material',
            name='shapes',
            field=models.ManyToManyField(to='app.shape'),
        ),
    ]
